# docker-compose.yml

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile # Certifique-se que este arquivo existe e é o do frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      # MANTIDO: Volume nomeado para persistir os dados do SQLite
      - sqlite_data:/app/data

volumes:
  sqlite_data:
    # driver: local # Padrão, mas pode ser explícito