FROM alpine:latest

RUN apk add --no-cache sqlite dcron

# Copia os scripts e o crontab
WORKDIR /scripts
COPY backup.sh .
COPY entrypoint.sh .
COPY crontab /etc/crontabs/root

# Dá permissão de execução para os scripts
RUN chmod +x backup.sh entrypoint.sh

# Define o entrypoint para ser o nosso script de inicialização
ENTRYPOINT ["/scripts/entrypoint.sh"]

# O CMD é removido, pois o entrypoint agora é o responsável por iniciar o cron