version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend-vue
    ports:
      - "8080:8080"
    volumes:
      - ./frontend-vue:/app
    stdin_open: true
    tty: true