version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do container para a porta 8080 da máquina
    container_name: frontend
    restart: always

  backend:
    build:
      context: .  # O contexto é o diretório raiz do projeto
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"  # Mapeia a porta 5001 do container para a porta 5001 da máquina
    container_name: backend
    restart: always