# Dockerfile.backend
# Usa uma imagem base do Node.js (versão 18)
FROM node:18

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência do diretório backend
COPY ./backend/package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código do backend
COPY ./backend .

# Expõe a porta 3000 (porta usada no server.js)
EXPOSE 3000

# Comando para rodar o backend
CMD ["node", "server.js"]
